Examples/DataSynthesizer-master/webUI/dataResponsiblyUI/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.base, name='base'),
    # url(r'^rankingfacts/', include('rankingfacts.urls')),
   # url(r'^dataflow/', include('dataflow.urls')),
    url(r'^synthesizer/', include('synthesizer.urls')),
    url(r'^admin/', admin.site.urls),

]
if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Examples/DataSynthesizer-master/webUI/synthesizer/urls.py
from django.conf.urls import url

from . import views

app_name = 'synthesizer'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^proc_data_dash/$', views.proc_data_dash, name='proc_data_dash'),
    url(r'^proc_json_processing/$', views.proc_json_processing, name='proc_json_processing'),

    url(r'^synthesizer_display/$', views.synthesizer_display, name='synthesizer_display'),
    url(r'^res_json_processing_plot/$', views.res_json_processing_plot, name='res_json_processing_plot'),
    url(r'^res_json_processing/$', views.res_json_processing, name='res_json_processing'),
    url(r'^res_json_processing_after/$', views.res_json_processing_after, name='res_json_processing_after'),

    url(r'^com_data/$', views.com_data, name='com_data'),
    url(r'^com_histogram/$', views.com_histogram, name='com_histogram'),
    url(r'^com_hitmap/$', views.com_hitmap, name='com_hitmap'),
]

Examples/DataSynthesizer-master/webUI/synthesizer/models.py
import json

import numpy as np
import pandas as pd


def save_uploaded_file(f, current_file):
    with open(current_file + ".csv", 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)


def chart_position_score(current_file):
    data = pd.read_csv(current_file)
    return_data = {'datapoint': [], 'top10': [], 'overall': []}
    score_value = data["Score"].tolist()
    position_value = [x for x in range(1, len(data) + 1)]
    for i in range(len(score_value)):
        return_data['datapoint'].append([position_value[i], score_value[i]])
    # get the median data
    attr_list = []
    for i in range(2, data.shape[1] - 1):
        attr_list.append(data.iloc[:, i].tolist())

    colname = data.columns[2:5]
    topTen = 10
    for i in range(len(attr_list)):
        return_data['top10'].append(
            [colname[i], max(attr_list[i][0:topTen]), np.median(attr_list[i][0:topTen]), min(attr_list[i][0:topTen])])
        return_data['overall'].append([colname[i], max(attr_list[i]), np.median(attr_list[i]), min(attr_list[i])])
    return return_data


def save_file_to_server(file_name, data):
    with open(file_name + ".txt", 'w') as outfile:
        outfile.write(str(data))
    outfile.close()


def get_json_from_file(file_name):
    with open(file_name, 'r') as myfile:
        json_data = myfile.read().replace('\n', '')
    return json_data
def getSizeOfDataset(current_file):
    """
    Compute number of rows in the input data.

    Attributes:
        current_file: file name that stored the data (with out ".csv" suffix)
    Return:  number of rows in current_file
    """
    data = pd.read_csv(current_file+".csv")
    return len(data)

class DataDescriberUI(object):
    """Analyze input dataset, then save the dataset description in a JSON file.
       Used to display in datatable.
    Attributes:
        threshold_size: float, threshold when size of input_dataset exceed this value, then only display first 100 row in input_dataset
        dataset_description: Dict, a nested dictionary (equivalent to JSON) recording the mined dataset information.

        input_dataset: the dataset to be analyzed.

    """

    def __init__(self, threshold_size=100):
        self.threshold_size = threshold_size
        self.dataset_description = {}
        self.input_dataset = None
        self.display_dataset = None
        self.json_data = {}

    def read_dataset_from_csv(self, file_name=None):
        file_name = file_name + ".csv"
        try:
            self.input_dataset = pd.read_csv(file_name)
        except (UnicodeDecodeError, NameError):
            self.input_dataset = pd.read_csv(file_name, encoding='latin1')

        num_tuples, num_attributes = self.input_dataset.shape
        if num_tuples > self.threshold_size:
            self.display_dataset = self.input_dataset.head(self.threshold_size)
        else:
            self.display_dataset = self.input_dataset

    def get_dataset_meta_info(self):
        num_tuples, num_attributes = self.input_dataset.shape
        attribute_list = self.input_dataset.columns.tolist()

        meta_info = {"num_tuples": num_tuples, "num_attributes": num_attributes, "attribute_list": attribute_list}
        self.dataset_description['meta'] = meta_info

    def get_json_data(self):
        self.json_data = self.display_dataset.to_json(orient='records')

    def save_dataset_description_to_file(self, file_name):
        with open(file_name, 'w') as outfile:
            json.dump(self.dataset_description, outfile, indent=4)

    def save_dataset_to_file(self, file_name):

        with open(file_name, 'w') as outfile:
            outfile.write(str(self.json_data))

    def display_dataset_description(self):
        print(json.dumps(self.dataset_description, indent=4))

Examples/DataSynthesizer-master/webUI/synthesizer/views.py
import json
import pandas as pd
from time import time

from django.urls import reverse
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render

import synthesizer.lib.DataSynthesizerWrapper as wrapper
from lib.utils import read_json_file
from .models import DataDescriberUI
from .models import save_uploaded_file
from .models import getSizeOfDataset


def index(request):
    play_data_list = ["adult_reduced","adult_with_missing_values","compas_reduced"]
    context = {"passed_play_data": play_data_list}
    # NOTICE: no .csv suffix in current passed file name
    server_data_names_map = {"adult_reduced": "AR", "adult_with_missing_values": "AM", "compas_reduced": "CR"}
    # create a time stamp for current uploading
    data_server_path = "./media/"
    play_data_server_path = "./playdata/synthesizer/"
    cur_time_stamp = str(int(time()*1e7))
    upload_data_size_threshold = 20
    if request.POST:
        if request.FILES:
            # get user upload file
            upload_csvfile = request.FILES['user_upload_data']
            current_data_name = data_server_path + cur_time_stamp
            save_uploaded_file(upload_csvfile, current_data_name)
            # get the size of uploaded data
            upload_data_size = getSizeOfDataset(current_data_name)
            context_size = {"passed_play_data": play_data_list, "passed_size_flag":"false"}
            # if upload data size less than the threshold, back to upload page and alert user
            if upload_data_size <= upload_data_size_threshold:
                return render(request, "synthesizer/index.html", context_size)

            request.session['passed_data_name'] = current_data_name
        else:
            selected_data = request.POST["dataset_select"]
            # create a copy of current play data set on server to allow differentiate multiple users at the same time
            cur_data = pd.read_csv(play_data_server_path + selected_data + ".csv")
            new_stamped_name = data_server_path + server_data_names_map[selected_data] + cur_time_stamp
            cur_data.to_csv(new_stamped_name + ".csv", index=False)
            request.session['passed_data_name'] = new_stamped_name
        return HttpResponseRedirect(reverse('synthesizer:proc_data_dash'))
    else:
        return render(request, "synthesizer/index.html", context)

def proc_data_dash(request):
    passed_data_name = request.session.get('passed_data_name')
    json_cate_info = wrapper.get_dataset_info(passed_data_name + ".csv")
    att_list = json_cate_info["attribute_list"]
    cat_att_list = json_cate_info["categorical_attributes"]
    key_att_list = json_cate_info['candidate_attributes']
    # json_header = []
    # for i in range(len(att_list)):
    #     json_header.append({"data": str(att_list[i])})
    # initialize json data and header for dataTables
    json_data_table = []
    json_header_table = []
    for i in range(len(att_list)):
        json_data_table.append({"data": str(att_list[i])})
        json_header_table.append({"title": str(att_list[i]), "targets": i})

    request.session['passed_json_columns'] = json_data_table
    request.session['passed_column_name'] = att_list

    data_type_list = []
    for i in att_list:
        data_type_list.append(json_cate_info["attribute_datatypes"][i])
    tuple_n = json_cate_info["number_of_tuples"]

    context = {'passed_data_name': passed_data_name, "passed_json_columns": json_data_table,
               "passed_column_name": att_list, "passed_json_columns_header": json_header_table,
               "passed_cat_atts": cat_att_list, "passed_att_types": data_type_list, "tuple_n": tuple_n,
               "passed_key_atts": key_att_list}

    return render(request, "synthesizer/proc_data_dash.html", context)


def proc_json_processing(request):
    passed_data_name = request.session.get('passed_data_name')

    up_data = DataDescriberUI()
    up_data.read_dataset_from_csv(passed_data_name)
    up_data.get_json_data()

    total_json = up_data.json_data

    return HttpResponse(total_json, content_type='application/json')


def res_json_processing(request):
    passed_data_name = request.session.get('passed_data_name')

    up_data = DataDescriberUI()
    up_data.read_dataset_from_csv(passed_data_name)
    up_data.get_json_data()

    total_json = up_data.json_data

    return HttpResponse(total_json, content_type='application/json')


def res_json_processing_after(request):
    passed_data_name = request.session.get('passed_data_name')

    up_data = DataDescriberUI()
    up_data.read_dataset_from_csv('{}_synthetic_data'.format(passed_data_name))
    up_data.get_json_data()

    total_json = up_data.json_data

    return HttpResponse(total_json, content_type='application/json')


def res_json_processing_plot(request):
    passed_data_name = request.session.get('passed_data_name')
    description_file = passed_data_name + "_plot.json"
    plot_json = read_json_file(description_file)
    return HttpResponse(json.dumps(plot_json), content_type='application/json')


def synthesizer_display(request):
    passed_data_name = request.session.get('passed_data_name')
    passed_json_columns = request.session.get('passed_json_columns')
    passed_column_name = request.session.get('passed_column_name')
    # generate dataTable data
    json_header_table = []
    for i in range(len(passed_column_name)):
        json_header_table.append({"title": str(passed_column_name[i]), "targets": i})


    mode_name = request.session.get('mode_name')
    passed_download_data = request.session.get('passed_download_data')
    passed_download_desp = request.session.get('passed_download_desp')


    context = {'passed_data_name': passed_data_name, "passed_json_columns": passed_json_columns,
               "passed_json_columns_header": json_header_table, "mode_name": mode_name,
               "passed_download_data": passed_download_data, "passed_download_desp": passed_download_desp}

    return render(request, 'synthesizer/com_data.html', context)


def com_data(request):
    passed_data_name = request.session.get('passed_data_name')
    passed_json_columns = request.session.get('passed_json_columns')
    passed_column_name = request.session.get('passed_column_name')
    # generate dataTable data
    json_header_table = []
    for i in range(len(passed_column_name)):
        json_header_table.append({"title": str(passed_column_name[i]), "targets": i})

    # get user input
    chosen_mode = request.POST['chose_mode']
    mode_id = chosen_mode.replace("mode", "")
    json_parameter = {}
    json_parameter["chose_mode"] = chosen_mode
    json_parameter["tuple_n"] = request.POST['tuple_N_m' + mode_id]
    json_parameter["categorical_atts"] = request.POST.getlist('checks_m' + mode_id)
    json_parameter["candidate_atts"] = request.POST.getlist('key_checks_m' + mode_id)
    # json_parameter["categorical_threshold"] = request.POST['cate_threshold_m' + mode_id]
    json_parameter["seed"] = request.POST['seed_m' + mode_id]

    mode_name = ""
    if mode_id != "1":
        json_parameter["histogram_size"] = request.POST['hist_size_m' + mode_id]
        json_parameter["epsilon"] = request.POST['epsilon_m' + mode_id]
        user_type_atts = {}
        for atti in passed_column_name:
            user_type_atts[atti] = request.POST[atti + "_m" + mode_id]

        json_parameter["type_atts"] = user_type_atts
    if mode_id == "3":
        json_parameter["max_degree"] = request.POST['max_degree']
    if mode_id == "1":
        mode_name = "Random Mode"
    if mode_id == "2":
        mode_name = "Independent Attribute Mode"
    if mode_id == "3":
        mode_name = "Correlated Attribute Mode"
    request.session["mode_name"] = mode_name
    # save user input parameters to server
    json_parameter_outputfn = passed_data_name + "_parameters.json"
    with open(json_parameter_outputfn, 'w') as outfile:
        json.dump(json_parameter, outfile, indent=4)

    wrapper.generate_data(passed_data_name)

    synthetic_data_name = passed_data_name + "_synthetic_data.csv"
    description_file = passed_data_name + "_description.json"
    wrapper.get_plot_data(passed_data_name + ".csv", synthetic_data_name, description_file)

    passed_download_data = synthetic_data_name.split("/media/")[1]
    passed_download_desp = description_file.split("/media/")[1]

    request.session["passed_download_data"] = passed_download_data
    request.session["passed_download_desp"] = passed_download_desp

    context = {'passed_data_name': passed_data_name, "passed_json_columns": passed_json_columns,
               "passed_json_columns_header": json_header_table, "mode_name": mode_name,
               "passed_download_data": passed_download_data, "passed_download_desp": passed_download_desp}
    return render(request, 'synthesizer/com_data.html', context)


def com_histogram(request):
    passed_data = request.session.get('passed_data_name')
    passed_json_columns = request.session.get('passed_json_columns')
    passed_column_name = request.session.get('passed_column_name')
    mode_name = request.session.get('mode_name')
    passed_download_data = request.session.get('passed_download_data')
    passed_download_desp = request.session.get('passed_download_desp')

    # get categorical attributes list
    cate_atts = wrapper.get_categorical_attributes(passed_data + '_plot.json')
    draw_atts = wrapper.get_drawable_attributes(passed_data + '_plot.json')
    context = {'passed_data_name': passed_data, "passed_json_columns": passed_json_columns,
               "passed_column_name": passed_column_name, "cate_column_name": cate_atts,
               "mode_name": mode_name, "drawable_atts": draw_atts,
               "passed_download_data": passed_download_data, "passed_download_desp": passed_download_desp}
    return render(request, 'synthesizer/com_histogram.html', context)


def com_hitmap(request):

Examples/DataSynthesizer-master/webUI/templates/synthesizer/com_data.html
{% load static %}
<head>
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


    <!-- Custom CSS -->
    <link href="{% static 'sbadmin/css/sb-admin-2-original.css' %}" rel="stylesheet">


    <!-- Custom Fonts -->
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <!-- DataTables CSS -->
    <link href="{% static 'datatables-plugins/dataTables.bootstrap.css' %}" rel="stylesheet">


    <link href="{% static 'others/css/landing-page.css' %}" rel="stylesheet">

    <!-- jQuery -->
    <script src="{% static 'jquery/jquery-3.2.1.min.js' %}"></script>
    <!-- dataTable -->
    <link href="{% static 'datatables/media/css/jquery.dataTables.css' %}" rel="stylesheet">
    <script src="{% static 'datatables/media/js/jquery.dataTables.js' %}"></script>

    <!-- Highcharts JavaScript -->
    <script src="{% static 'highcharts/code/highcharts.js' %}"></script>
    <script src="{% static 'highcharts/code/modules/exporting.js' %}"></script>
    <script src="https://code.highcharts.com/modules/gray.js"></script>

</head>

<body>
<div id="wrapper">
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand"><h3>Synthetic Data</h3></a>
        </div>
        <!-- /.navbar-header -->

        <ul class="nav navbar-top-links navbar-right">
            <div>
                <img src="{% static 'images/header_logo_grey_small.jpg' %}" class="img-responsive"
                     style="padding-top: 5px">
            </div>
        </ul>
        <!-- /.navbar-top-links -->

        <div class="navbar-default sidebar" role="navigation">
            <div class="sidebar-nav navbar-collapse">
                <ul class="nav" id="side-menu">
                    <li>
                        <a id="data_com_link" href="{% url 'synthesizer:synthesizer_display' %}"><i class="fa fa-table fa-fw"></i>
                            Data Comparison</a>
                    </li>
                    <li>
                        <a href="{% url 'synthesizer:com_histogram' %}"><i class="fa fa-bar-chart-o fa-fw"></i>
                            Histogram Comparison </a>
                    </li>
                    <li>
                        <a href="{% url 'synthesizer:com_hitmap' %}"><i class="fa fa-bar-chart-o fa-fw"></i>
                            Heatmap Comparison</a>
                    </li>
                    <br><br><br>
                    <li>
                        <a id="download_data" href="{{ MEDIA_URL }}{{ passed_download_data }}" download="{{ passed_download_data }}"
                           class="btn btn-outline btn-success">Download synthetic data</a>
                    </li>
                    <br>
                    <li>
                        <a id="download_desp" href="{{ MEDIA_URL }}{{ passed_download_desp }}" download="{{ passed_download_desp }}"
                           class="btn btn-outline btn-success">Download dataset description</a>
                    </li>
                    <img id="res_dt_logo" src="{% static 'images/DataSynthesizer_Logo.png' %}" class="img-responsive">

                </ul>
            </div>
        </div>
        <!-- /.navbar-static-side -->
    </nav>


    <div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Data comparison: input vs. synthetic ({{ mode_name }})</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-info" , style="display: none">
                    <div class="panel-heading">
                        <h4 class="panel-title">Instructions</h4>
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <p>Use navigation bar on the left to see a different comparison.</p>
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
        </div>
        <!-- /.row -->
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h5 class="panel-title"> Original data (top 100 rows)</h5>
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <!--<table width="100%" class="table table-striped table-bordered table-hover"-->
                               <!--id="data_table_original">-->
                            <!--<thead>-->
                            <!--</thead>-->
                        <!--</table>-->
                        <table id="data_table_original" class="display nowrap" cellspacing="0" width="100%">
                        </table>
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h5 class="panel-title"> Synthetic data (top 100 rows)</h5>
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <!--<table width="100%" class="table table-striped table-bordered table-hover"-->
                               <!--id="data_table_synthetic">-->
                            <!--<thead>-->
                            <!--</thead>-->
                        <!--</table>-->
                        <table id="data_table_synthetic" class="display nowrap" cellspacing="0" width="100%">
                        </table>
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
        </div>
        <!-- /.row -->
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="form-inline" align="center">
                            <a href="{% url 'synthesizer:proc_data_dash' %}" class="btn btn-default">Previous step
                                (Parameter settings)</a>
                            <a href="{% url 'synthesizer:index' %}" class="btn btn-default">Upload new dataset</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.row -->
    </div>
    <!-- /#page-wrapper -->
    <!--<div id="loadingImg">Loading&#8230;</div>-->
</div>
<!-- /#wrapper -->


<script type="text/javascript" language="javascript">
    //highlight data comparison link
    $("#data_com_link").trigger('click');

    $(document).ready(function () {
        $('#data_table_original').dataTable({
            ajax: {
                "url": "{% url 'synthesizer:res_json_processing' %}",
                "dataSrc": ""
            },
            columns: {{passed_json_columns | safe}},
            columnDefs: {{passed_json_columns_header | safe}},
            order: [[ 0, "desc" ]],
            scrollX: true,
        });
        $('#data_table_synthetic').DataTable({
            "ajax": {
                "url": "{% url 'synthesizer:res_json_processing_after' %}",
                "dataSrc": ""
            },
            columns: {{passed_json_columns | safe}},
            columnDefs: {{passed_json_columns_header | safe}},
            order: [[ 0, "desc" ]],
            scrollX: true,
        });

    });

</script>

<!-- Bootstrap Core JavaScript -->
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>

Examples/DataSynthesizer-master/webUI/templates/synthesizer/index.html
{% load static %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="DataResponsibly">
    <meta name="author" content="Drexel database group">

    <title>Data Responsibly</title>
    <meta name="description" content="DataResponsibly is a project that aims to make data management responsible.">

    <!-- CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'others/css/fileinput.min.css' %}" rel="stylesheet">
    <link href="{% static 'others/css/landing-page.css' %}" rel="stylesheet">
    <!-- bootstrap-select -->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.3/css/bootstrap-select.min.css" />
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet"
          type="text/css">
    <script src="{% static 'jquery/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</head>

<body>

<div class="intro-header">
    <div class="container">

        <div class="row">
            <div class="col-lg-12">
                <div class="navbar-header">
                    <div class="navbar-brand navbar-left">
                        <img id="dt_logo" style="margin-top: -45px;" class="img-responsive"
                             src="{% static 'images/rsz_datasynthesizer_logo.png' %}">
                    </div>
                    <div class="navbar-brand navbar-right">
                        <img style="margin-top: -7px;" class="img-responsive" src="{% static 'images/rsz_header_logo.png' %}">
                    </div>
                    <div class="intro-message">
                        <h1>Data Synthesizer</h1>
                        <hr class="intro-divider">
                        <form method="post" enctype="multipart/form-data">{% csrf_token %}
                            <h2>Upload your own data</h2>
                            <input id="file_upload" type="file" accept=".csv" class="filestyle" data-icon="false" name="user_upload_data" onchange='triggerValidation(this)' />
                            <br>
                            <h2>OR</h2>
                            <br>
                            <h2>Play with our test data <span>&nbsp;&nbsp;</span> <a style="color: #0f0f0f" data-toggle="tooltip" data-placement="right"><i class="fa fa-question-circle fa-1x"></i></a></h2>
                            <select id="dataset_select" name="dataset_select" class="selectpicker">
                                {% for datai in passed_play_data %}
                                 <option value="{{ datai | safe }}">{{ datai }}</option>
                                {% endfor %}
                            </select>


                            <span><br><br><br><br></span>
                            <input id="upload_btn" class="btn btn-default btn-lg top-buffer" aria-haspopup="true"
                                   aria-expanded="false" type="submit" value="Upload Data"/>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- FOOTER -->
<div class="footer_div">
    <div class="container_footer">
        <footer class="main_footer">
            <p class="text-muted">
                &copy; 2017 <a href="https://github.com/DataResponsibly/DataSynthesizer"> Data Synthesizer GitHub</a>
                | <a href="https://dataresponsibly.github.io">Data Responsibly</a>
                | <a href="https://dataresponsibly.github.io/contact/">Contact Us</a>
            </p>
        </footer>
    </div>
</div>

<style>

    .main_footer {
        background: inherit;
    }

    .container_footer {
        display: flex;
        justify-content: center;
    }

</style>

<!-- play data toolip setting-->
<script type="text/javascript" language="javascript">
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip({
        title: "All the test datasets here are sample datasets. The original datasets can be found in our GitHub repository. Check the code link in the footer of this page!",
        });
});
</script>
<!-- if upload data size less than threshold, then alert user to upload new data or leave it blank use test data-->
<script type="text/javascript" language="JavaScript">
    // validate upload data size
    var data_size_flag = {{passed_size_flag | safe}};
    if (data_size_flag == false){
        alert("You need to upload a data set that has more than 20 rows! Or leave it blank to use our test data!");
    }
</script>
<!-- if upload data is not .csv file, then alert user to upload new data or leave it blank to use test data-->
<script type="text/javascript" language="javascript">
    // for browser that does not support .csv accept
    var regex = new RegExp("(.*?)\.(csv)$");

    function triggerValidation(el) {
      if (!(regex.test(el.value.toLowerCase()))) {
        el.value = '';
        alert('Please upload a .csv file!');
      }
    }

</script>



<!-- JavaScript -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="{% static 'others/js/bootstrap-filestyle.min.js' %}"></script>
<script src="{% static 'others/js/fileinput.min.js' %}"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.6.3/js/bootstrap-select.min.js"></script>

</body>
</html>